config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get '/auth/twitter/callback', to: 'sessions#create', as: 'callback'
  get '/auth/failure', to: 'sessions#error', as: 'failure'
  get '/profile', to: 'sessions#show', as: 'show'
  delete '/signout', to: 'sessions#destroy', as: 'signout'

  get '/user/:name', to: 'users#show', as: 'user'

  get '/collection/new', to: 'collections#new', as: 'new_collection'
  post '/collection', to: 'collections#create', as: 'create_collection'
  get '/collection/:slug(.:format)', to: 'collections#show', as: 'collection'
  delete '/collection/:slug', to: 'collections#destroy', as: 'destroy_collection'

  post '/tweets/create', to: 'tweets#create', as: 'create_tweet'
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  extend FriendlyId

  friendly_id :name, use: [:slugged, :history]

  has_many :privileges
  has_many :users, through: :privileges

  validates_uniqueness_of :slug

  has_many :tweets

  def public?
    !private?
  end

  def should_generate_new_friendly_id?
    new_record? || slug.blank?
  end

  def contributors
    privileges.map(&:user).uniq
  end

  def visible_to? user
    if public?
      true
    elsif user.blank?
      false
    else
      privileges.where(user: user).any?
    end
  end

  def can_add? user
    privs = privileges.where(user: user)
    privs.present? && [:add, :edit, :owner].include?(privs.last.level.to_sym)
  end

  def can_edit? user
    privs = privileges.where(user: user)
    privs.present? && [:edit, :owner].include?(privs.last.level.to_sym)
  end
end

app/models/privilege.rb
class Privilege < ActiveRecord::Base
  belongs_to :user
  belongs_to :collection

  enum level: [:read, :add, :edit, :owner]
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :collection

  validates_presence_of :url
  validates_format_of :url, :with => URI::regexp(%w(http https))
  #TODO: validate that the url is a twitter permalink

end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId

  friendly_id :name

  has_many :privileges
  has_many :collections, through: :privileges

  validates_uniqueness_of :name

  after_create :generate_default_collection

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["nickname"]
      user.access_token = auth["credentials"]["token"]
      user.access_token_secret = auth["credentials"]["secret"]
    end
  end

  private

  def generate_default_collection
    collection = Collection.create(name: "@#{self.name}'s Favorites")
    Privilege.create(user: self, collection: collection, level: :owner)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  def not_allowed
    raise ActionController::RoutingError.new('Not Allowed')
  end

private

  def current_user
    user_id = cookies.permanent.signed[:user_id]
    logger.info "user_id: #{user_id}"
    @current_user ||= User.find_by_uid(user_id) if user_id.present?
  end
  helper_method :current_user

  def client
    @client ||= Twitter::REST::Client.new do |config|
      config.consumer_key = ENV['CONSUMER_KEY']
      config.consumer_secret = ENV['CONSUMER_SECRET']
      config.access_token = current_user.access_token
      config.access_token_secret = current_user.access_token_secret
    end
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def new
    not_allowed unless current_user

    @collection = Collection.new
  end

  def create
    not_allowed unless current_user

    @collection = Collection.create(collection_params)
    Privilege.create(user: current_user, collection: @collection, level: :owner)

    redirect_to @collection, {notice: 'Created!', status: :see_other}
  end

  def show
    @collection = Collection.friendly.find(params[:slug])

    not_found unless @collection.public? || @collection.visible_to?(current_user)

    #handle renamed collections
    if request.path != collection_path(@collection, params)
      return redirect_to @collection, status: :moved_permanently
    end

    respond_to do |format|
      format.html
      format.text { render text: @collection.tweets.map(&:url).join('\n') }
    end
  end

  private

  def collection_params
    params.require(:collection).permit(:name, :description, :private)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    unless current_user
      auth = request.env['omniauth.auth']
      user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) ||
             User.create_with_omniauth(auth)
      cookies.permanent.signed[:user_id] = user.uid
    end

    if current_user.present?
      redirect_to current_user, notice: 'Signed in'
    else
      error
    end
  end

  def show
    if current_user
      @twitter_user = client.user(include_entities: true)
    else
      redirect_to failure_path
    end
  end

  def error
    flash[:error] = 'Sign in with Twitter failed'
    redirect_to root_path
  end

  def destroy
    cookies.delete :user_id
    redirect_to root_path, notice: 'Signed out'
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def create
    collection = Collection.friendly.find(collection_params)

    not_allowed unless current_user

    privs = Privilege.where(user: current_user).where(collection: collection).last
    not_allowed unless privs.present?
    not_allowed unless [:add, :edit, :owner].to_s.include?(privs.level)

    not_found unless collection.present?

    tweet = Tweet.create(url: params[:url], collection: collection)
    redirect_to collection, {notice: 'Added!', status: :see_other}
  end

  private

  def collection_params
    params.require(:collection_slug)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.friendly.find(user_params)

    collections = @user.collections.all.order(updated_at: :desc)
    @visible_collections = collections.select {|c| c.visible_to?(current_user)}
    render
  end

  private

  def user_params
    params.require(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      redirect_to current_user
    end


  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Twitter::Autolink
end

app/helpers/collections_helper.rb
module CollectionsHelper
  def curated_by users
    "Curated by " + users.map {|u| link_to "@#{u.name}", u}.to_sentence
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/collections/new.html.haml
= form_for(@collection, url: create_collection_path) do |f|
  %fieldset
    = f.label :name, "Name"
    = f.text_field :name

  %fieldset
    = f.label :description, "Description (optional)"
    = f.text_field :description

  %fieldset
    = f.label :private, "Private collection"
    = f.check_box :private, value: false

  %fieldset
    = f.submit "Submit", class: 'btn btn-primary'

app/views/collections/show.html.haml
.row
  .span6
    %h1
      = @collection.name
    %h2
      = @collection.description
    %h3
      = curated_by(@collection.contributors).html_safe
  .span4.offset1
    = link_to('Delete', destroy_collection_path(@collection), class: 'btn btn-danger', method: :delete, confirm: 'Are you sure?')
    = link_to('Export', collection_path(@collection, format: 'txt'), class: 'btn btn-primary')

.row
  .span6.offset3
    - @collection.tweets.each do |tweet|
      .row
        %blockquote.twitter-tweet
          %a{href: tweet.url}
            = tweet.url

- if @collection.can_add?(current_user)
  .row
    .span4.offset4
      = render 'tweets/form', locals: {collection: @collection}

:javascript
  window.twttr = (function (d, s, id) {
    var t, js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src= "https://platform.twitter.com/widgets.js";
    fjs.parentNode.insertBefore(js, fjs);
    return window.twttr || (t = { _e: [], ready: function (f) { t._e.push(f) } });
  }(document, "script", "twitter-wjs"));

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      = t('app.name')
    %meta{charset: 'utf-8'}
    %meta{name: 'author', content: t('app.author')}
    %meta{name: 'description', content: t('app.description')}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
    = csrf_meta_tags
    %link{rel: 'shortcut icon', href: '/favicon.ico'}
    / HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
      = javascript_include_tag 'http://html5shim.googlecode.com/svn/trunk/html5.js'
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js'
    = javascript_include_tag 'application'
  %body
    .navbar
      .navbar-inner
        .container
          %a.btn.btn-navbar{:'data-toggle' => 'collapse', :'data-target' => '.nav-collapse'}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to('Would Fav', root_path, class: 'brand')
          .nav-collapse
            %ul.nav
              - if current_user
                %li
                  = link_to(t('nav.profile'), current_user)
                %li
                  = link_to(t('button.sign_out'), signout_path, method: :delete)
              - else
                %li
                  = link_to(t('button.sign_in'), '/auth/twitter')
    .container
      - if flash[:notice]
        .alert
          %a{class: 'close', :'data-dismiss' => 'alert', href: '#'}
            &times;
          = flash[:notice]
        :javascript
          $('.alert').alert();
      - if flash[:error]
        .alert.alert-error
          %a{class: 'close', :'data-dismiss' => 'alert', href: '#'}
            &times;
          = flash[:error]
        :javascript
          $('.alert').alert();
      = yield
      %footer
        %p
          = "#{t('app.author')} made this".downcase.html_safe

app/views/tweets/_form.html.haml
= form_for(:tweet, url: create_tweet_path) do |f|
  = hidden_field_tag :collection_slug, @collection.slug
  = label_tag :url, "URL"
  = text_field_tag :url, ""
  = submit_tag "Submit"

app/views/users/show.html.haml
.row
  .span6
    %h1
      = @user.name
  - if @user == current_user
    .span4.offset1
      = link_to('New Collection', new_collection_path, class: 'btn btn-success')

.row
  .span8
    %table.table
      %thead
        %tr
          %th
            Collection
          %th
            Tweets
          %th
            Last Updated
          %th
            Public?
          %th
            Access
      %tbody
        - @visible_collections.each do |collection|
          - privs = Privilege.where(user: @user).where(collection: collection).last.level
          %tr
            %td
              = link_to collection.name, collection
            %td
              = collection.tweets.size
            %td
              = "#{time_ago_in_words(collection.updated_at)} ago"
            %td
              = collection.public?.to_s
            %td
              = privs.capitalize

app/views/welcome/index.html.haml
.row
  .span14
    = form_tag '/auth/twitter', method: 'get', html: {class: 'form-horizontal'} do
      %fieldset
        %legend
          = t('app.description_html')
        .form-actions
          %p.help-block
            = t('help.sign_in')
          %button.btn.btn-large.btn-primary
            = t('button.sign_in')